# node name conversion method to conert from from HGNC.symbols to node names in the Park network 
library(dplyr)

node_name_conversion <- function(df) {
  df$source <-  ifelse(df$source == "AKT1", "Akt",
                ifelse(df$source %in% c("PDK1", "PDPK1"), "PDK1",
                ifelse(df$source == "TP53", "p53",
                ifelse(df$source == "PRKAA2", "AMPK",
                ifelse(df$source %in% c("ATF2", "GDNF"), "ATF2",
                ifelse(df$source %in% c("ELK1", "KCNH4"), "ELK1",
                ifelse(df$source %in% c("MAPK1", "EPHB2"), "ERK",
                ifelse(df$source == "GSK3beta", "GSK3beta",
                ifelse(df$source == "MAPK8", "JNK",
                ifelse(df$source == "RPS6KA1", "p90RSK",
                ifelse(df$source %in% c("MAPK14", "AHSA1", "AIMP2"), "p38",
                ifelse(df$source == "PPM1D", "Wip1",
                ifelse(df$source == "BAX", "Bax",
                ifelse(df$source == "RPS6KB1", "S6K",
                ifelse(df$source == "SOAT1","STAT", 
                ifelse(df$source == "BRAF","Braf", 
                ifelse(df$source == "Ras", "Ras",
                ifelse(df$source == "SRC","Src", 
                ifelse(df$source == "CHEK2","CHK2", 
                ifelse(df$source ==  "CHEK1","CHK1",
                ifelse(df$source %in%  c("RASGRF1","CDC25C"),"Cdc25",
                ifelse(df$source == "MAPKAPK2","MK2",
                ifelse(df$source == "RAF1","Craf", 
                ifelse(df$source == "SIK1","MSK", 
                ifelse(df$source %in% c("CDKN1A","TCEAL1"),"p21", 
                ifelse(df$source %in% c("H3P23","IFI27","PSMD9","ZNRD2"),"p27",
                ifelse(df$source == "RB1","Rb", 
                ifelse(df$source %in% c("H3P9","MRPL28","NXT1","CDKN2B","SUB1"),"p15", 
                ifelse(df$source == "CDKN2A","p14ARF",
                ifelse(df$source %in% c("GAB1","PIGU"),"GAB1", 
                ifelse(df$source == "GRB2","Grb2",
                ifelse(df$source == "SHC1", "Shc",
                ifelse(df$source == "IGF1R", "IGFR",
                ifelse(df$source == "MAP2K4", "MKK4",
                ifelse(df$source == "MAP2K7", "MKK7",
                ifelse(df$source == "MDM4", "MDMX",
                ifelse(df$source == "MAP3K1", "MEKK1",
                ifelse(df$source == "MAP3K2", "MEKK2",
                ifelse(df$source == "MAP3K3", "MEKK3",
                ifelse(df$source %in% c("NR2C2","MAP3K7"), "TAK1", 
                ifelse(df$source == "MAP3K4", "MEKK4", 
                ifelse(df$source == "PIK3CA", "PI3K", 
                ifelse(df$source == "RASA1", "p120RasGAP", 
                ifelse(df$source == "PTPN11","SHP2", 
                ifelse(df$source %in% c("RAC1", "RNASE1"), "Rac1", 
                ifelse(df$source == "DIABLO", "SMAC", 
                ifelse(df$source == "Smad7", "SMAD7", df$source)))))))))))))))))))))))))))))))))))))))))))))))
  return(df)
}